version: '3'
services:
  my-api:
    build: .
    ports:
      - '3000:3000'
    container_name: my-api
  planner-app:
    build: ../Planner
    container_name: planner-app
  nginx-planner:
    image: nginx:alpine
    container_name: nginx-planner
    ports:
      - "80:5000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - planner-app

  